using System;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Kinlo.AutoCodeGenerator
{
  [Generator]
  public class InterfaceGenerator : IIncrementalGenerator
  {
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
      var classDeclarations = context
        .SyntaxProvider.CreateSyntaxProvider(
          predicate: static (node, _) => node is ClassDeclarationSyntax,
          transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node
        )
        .Where(static c =>
          c.AttributeLists.SelectMany(a => a.Attributes).Any(attr => attr.Name.ToString().Contains("BatteryDisplay"))
        )
        .Combine(context.CompilationProvider);

      context.RegisterSourceOutput(
        classDeclarations,
        (spc, source) =>
        {
          var (classDeclaration, compilation) = source;

          var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);

          if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return;

          var interfaceName = $"I{classSymbol.Name}";

          var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? "Generated"
            : classSymbol.ContainingNamespace.ToDisplayString();

          // 只取当前类自己定义的 public 属性
          var properties = classSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p =>
              p.DeclaredAccessibility == Accessibility.Public
              && p.ContainingType.Equals(classSymbol, SymbolEqualityComparer.Default)
            )
            .ToList();

          // 只取当前类自己定义的 public 方法
          var methods = classSymbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m =>
              m.MethodKind == MethodKind.Ordinary
              && m.DeclaredAccessibility == Accessibility.Public
              && !m.IsStatic
              && m.ContainingType.Equals(classSymbol, SymbolEqualityComparer.Default)
            )
            .ToList();

          // =========================================================
          // 生成 Interface
          // =========================================================

          var sb = new StringBuilder();

          sb.AppendLine("// <auto-generated />");
          sb.AppendLine("using System;");
          sb.AppendLine();

          sb.AppendLine($"namespace {namespaceName}");
          sb.AppendLine("{");
          sb.AppendLine($"    public interface {interfaceName}");
          sb.AppendLine("    {");

          // 索引器
          sb.AppendLine("        /// <summary>");
          sb.AppendLine("        /// 按属性名称获取或设置值");
          sb.AppendLine("        /// </summary>");
          sb.AppendLine("        object this[string name] { get; set; }");
          sb.AppendLine();

          // =========================================================
          // 属性
          // =========================================================

          foreach (var prop in properties)
          {
            var summary = GetSummary(prop);

            if (!string.IsNullOrWhiteSpace(summary))
            {
              sb.AppendLine("        /// <summary>");

              AppendXmlComment(sb, summary, 8);

              sb.AppendLine("        /// </summary>");
            }

            sb.AppendLine(
              $"        {prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} {prop.Name} {{ get; set; }}"
            );

            sb.AppendLine();
          }

          // =========================================================
          // 方法
          // =========================================================

          foreach (var method in methods)
          {
            var xml = method.GetDocumentationCommentXml();

            if (!string.IsNullOrWhiteSpace(xml))
            {
              try
              {
                var xmlDoc = XDocument.Parse(xml);

                // summary
                var summary = xmlDoc.Descendants("summary").FirstOrDefault()?.Value;

                if (!string.IsNullOrWhiteSpace(summary))
                {
                  sb.AppendLine("        /// <summary>");

                  AppendXmlComment(sb, summary, 8);

                  sb.AppendLine("        /// </summary>");
                }

                // param
                foreach (var param in xmlDoc.Descendants("param"))
                {
                  var nameAttr = param.Attribute("name");

                  if (nameAttr != null)
                  {
                    var paramName = nameAttr.Value;
                    var paramDesc = param.Value.Trim();

                    sb.AppendLine($"        /// <param name=\"{paramName}\">{paramDesc}</param>");
                  }
                }

                // returns
                var returns = xmlDoc.Descendants("returns").FirstOrDefault()?.Value.Trim();

                if (!string.IsNullOrWhiteSpace(returns))
                {
                  sb.AppendLine($"        /// <returns>{returns}</returns>");
                }
              }
              catch
              {
                // 忽略 XML 解析错误
              }
            }

            var parameters = string.Join(
              ", ",
              method.Parameters.Select(p =>
              {
                var typeName = p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

                return $"{typeName} {p.Name}";
              })
            );

            sb.AppendLine(
              $"        {method.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} {method.Name}({parameters});"
            );

            sb.AppendLine();
          }

          sb.AppendLine("    }");
          sb.AppendLine("}");

          spc.AddSource($"{interfaceName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

          // =========================================================
          // 生成 partial class
          // =========================================================

          var partialClass = new StringBuilder();

          partialClass.AppendLine("// <auto-generated />");
          partialClass.AppendLine("using System;");
          partialClass.AppendLine();

          partialClass.AppendLine($"namespace {namespaceName}");
          partialClass.AppendLine("{");

          partialClass.AppendLine($"    partial class {classSymbol.Name} : {interfaceName}");

          partialClass.AppendLine("    {");

          partialClass.AppendLine("        [ExpressionDeepSync(true)]");
          partialClass.AppendLine("        [SugarColumn(IsIgnore = true)]");

          partialClass.AppendLine("        public object this[string name]");
          partialClass.AppendLine("        {");

          // getter
          partialClass.AppendLine("            get");
          partialClass.AppendLine("            {");
          partialClass.AppendLine("                return name switch");
          partialClass.AppendLine("                {");

          foreach (var prop in properties)
          {
            partialClass.AppendLine($"                    nameof({classSymbol.Name}.{prop.Name}) => this.{prop.Name},");
          }

          partialClass.AppendLine(
            "                    _ => throw new global::System.ArgumentException($\"未找到属性 {name}\")"
          );

          partialClass.AppendLine("                };");
          partialClass.AppendLine("            }");

          // setter
          partialClass.AppendLine();
          partialClass.AppendLine("            set");
          partialClass.AppendLine("            {");
          partialClass.AppendLine("                switch (name)");
          partialClass.AppendLine("                {");

          foreach (var prop in properties)
          {
            var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

            partialClass.AppendLine($"                    case nameof({classSymbol.Name}.{prop.Name}):");

            partialClass.AppendLine($"                        this.{prop.Name} = ({typeName})value!;");

            partialClass.AppendLine("                        break;");
          }

          partialClass.AppendLine(
            "                    default: throw new global::System.ArgumentException($\"未找到属性 {name}\");"
          );

          partialClass.AppendLine("                }");
          partialClass.AppendLine("            }");

          partialClass.AppendLine("        }");

          partialClass.AppendLine("    }");
          partialClass.AppendLine("}");

          spc.AddSource(
            $"{classSymbol.Name}_Implements_{interfaceName}.g.cs",
            SourceText.From(partialClass.ToString(), Encoding.UTF8)
          );
        }
      );
    }

    /// <summary>
    /// 获取 XML summary
    /// </summary>
    private static string? GetSummary(ISymbol symbol)
    {
      var xml = symbol.GetDocumentationCommentXml();

      if (string.IsNullOrWhiteSpace(xml))
        return null;

      try
      {
        var xmlDoc = XDocument.Parse(xml);

        return xmlDoc.Descendants("summary").FirstOrDefault()?.Value.Trim();
      }
      catch
      {
        return null;
      }
    }

    /// <summary>
    /// 追加 XML 注释（支持多行）
    /// </summary>
    /// <param name="sb"></param>
    /// <param name="text"></param>
    /// <param name="indent"></param>
    private static void AppendXmlComment(StringBuilder sb, string text, int indent = 8)
    {
      if (string.IsNullOrWhiteSpace(text))
        return;

      string prefix = new string(' ', indent);

      var lines = text.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

      foreach (var line in lines)
      {
        var trimLine = line.Trim();

        if (string.IsNullOrWhiteSpace(trimLine))
          continue;

        sb.AppendLine($"{prefix}/// {trimLine}");
      }
    }
  }
}
