//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendAndCheckService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.server.linkmes.wisdytech.com/", ConfigurationName="SendAndCheckService.EquipWebServiceAction")]
    public interface EquipWebServiceAction
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getWGJCResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upFirstPieceDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getKeyParamLimitAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getYCResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAGVMaterialResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> UpMESCartonDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDOUBLEZJPHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOCV1ResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCSBHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getMYLARResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getWGJCDMFORCELLDATEResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upCrossScrapQtyAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOCV4ResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCSBPDResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upHCOUTStateAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCellDataForFxAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getYcZyDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCSBJLHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getEqBomResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GetKMResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCellSealResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getStopSignalAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCCDDataForJRAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZJPKMResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> UpEquipFDAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upMFWIPAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getBMLMRKResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getMFDHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getBMWYCHResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getTSBHResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getBMResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getRKFrontResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getShopNameAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getLKFXResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDoubleCSBHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getHCFROCVFinishResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getInventoryWIPWarningAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getWIPCodeAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getRYResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getFirstVersionAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getQjResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getJrResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getJEJGHResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getRKBackResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOCV4DataForOCV53Async(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCSBYHResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getPDResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getWGJCDMResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upCellProcedureNameAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getECZYResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> UpMESBoxtDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZYFeedingResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GetLyResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getrkmaterialAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getProductCodeAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDGKMResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZJPTJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCellProcessDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCellModelAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZJMQResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GetCellHistoryDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="dcsWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getTBFeedingMaterialResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> UpYczyByAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDGHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCellGradeAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDXHKResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOCV0ResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCellOrderDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getFXResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCellWaterResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> CheckCartonDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getIDCardCheckAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upHCINStateAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="dcsWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getTBFeedingWIPResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upMaterailScrapAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upScarapQtyAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOCV3ResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getMHYHResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upCheckWaterResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getYcZyDataSAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upFROUTStateAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upFRINStateAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> CheckMESBoxtDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getFJMQResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getUserOpCodesAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getYCHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOCV2ResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upCartonDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getFirstProcessAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getHCFRResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> checkOperatorAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getYCZYResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getXRAYResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upCellExceptionStateAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOCV3DataForOCV4Async(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getZJPHJResultAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getNGCodeAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="equipWebService", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> upRealtimeStatusAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface EquipWebServiceActionChannel : SendAndCheckService.EquipWebServiceAction, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class EquipWebServiceActionClient : System.ServiceModel.ClientBase<SendAndCheckService.EquipWebServiceAction>, SendAndCheckService.EquipWebServiceAction
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EquipWebServiceActionClient() : 
                base(EquipWebServiceActionClient.GetDefaultBinding(), EquipWebServiceActionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EquipWebServiceActionPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EquipWebServiceActionClient(EndpointConfiguration endpointConfiguration) : 
                base(EquipWebServiceActionClient.GetBindingForEndpoint(endpointConfiguration), EquipWebServiceActionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EquipWebServiceActionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EquipWebServiceActionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EquipWebServiceActionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EquipWebServiceActionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EquipWebServiceActionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> getWGJCResultAsync(string data)
        {
            return base.Channel.getWGJCResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upFirstPieceDataAsync(string data)
        {
            return base.Channel.upFirstPieceDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getKeyParamLimitAsync(string data)
        {
            return base.Channel.getKeyParamLimitAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getYCResultAsync(string data)
        {
            return base.Channel.getYCResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getAGVMaterialResultAsync(string data)
        {
            return base.Channel.getAGVMaterialResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> UpMESCartonDataAsync(string data)
        {
            return base.Channel.UpMESCartonDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getDOUBLEZJPHJResultAsync(string data)
        {
            return base.Channel.getDOUBLEZJPHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getOCV1ResultAsync(string data)
        {
            return base.Channel.getOCV1ResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCSBHJResultAsync(string data)
        {
            return base.Channel.getCSBHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getMYLARResultAsync(string data)
        {
            return base.Channel.getMYLARResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getWGJCDMFORCELLDATEResultAsync(string data)
        {
            return base.Channel.getWGJCDMFORCELLDATEResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upCrossScrapQtyAsync(string data)
        {
            return base.Channel.upCrossScrapQtyAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getZHJResultAsync(string data)
        {
            return base.Channel.getZHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getOCV4ResultAsync(string data)
        {
            return base.Channel.getOCV4ResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCSBPDResultAsync(string data)
        {
            return base.Channel.getCSBPDResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upHCOUTStateAsync(string data)
        {
            return base.Channel.upHCOUTStateAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCellDataForFxAsync(string data)
        {
            return base.Channel.getCellDataForFxAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getYcZyDataAsync(string data)
        {
            return base.Channel.getYcZyDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCSBJLHJResultAsync(string data)
        {
            return base.Channel.getCSBJLHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getEqBomResultAsync(string data)
        {
            return base.Channel.getEqBomResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> GetKMResultAsync(string data)
        {
            return base.Channel.GetKMResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCellSealResultAsync(string data)
        {
            return base.Channel.getCellSealResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getStopSignalAsync(string data)
        {
            return base.Channel.getStopSignalAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCCDDataForJRAsync(string data)
        {
            return base.Channel.getCCDDataForJRAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getZJPKMResultAsync(string data)
        {
            return base.Channel.getZJPKMResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> UpEquipFDAsync(string data)
        {
            return base.Channel.UpEquipFDAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upMFWIPAsync(string data)
        {
            return base.Channel.upMFWIPAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getBMLMRKResultAsync(string data)
        {
            return base.Channel.getBMLMRKResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getMFDHJResultAsync(string data)
        {
            return base.Channel.getMFDHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getBMWYCHResultAsync(string data)
        {
            return base.Channel.getBMWYCHResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getTSBHResultAsync(string data)
        {
            return base.Channel.getTSBHResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getBMResultAsync(string data)
        {
            return base.Channel.getBMResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getRKFrontResultAsync(string data)
        {
            return base.Channel.getRKFrontResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getShopNameAsync(string data)
        {
            return base.Channel.getShopNameAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getLKFXResultAsync(string data)
        {
            return base.Channel.getLKFXResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getDoubleCSBHJResultAsync(string data)
        {
            return base.Channel.getDoubleCSBHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getHCFROCVFinishResultAsync(string data)
        {
            return base.Channel.getHCFROCVFinishResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getInventoryWIPWarningAsync(string data)
        {
            return base.Channel.getInventoryWIPWarningAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getWIPCodeAsync(string data)
        {
            return base.Channel.getWIPCodeAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getRYResultAsync(string data)
        {
            return base.Channel.getRYResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getFirstVersionAsync(string data)
        {
            return base.Channel.getFirstVersionAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getQjResultAsync(string data)
        {
            return base.Channel.getQjResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getJrResultAsync(string data)
        {
            return base.Channel.getJrResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getJEJGHResultAsync(string data)
        {
            return base.Channel.getJEJGHResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getRKBackResultAsync(string data)
        {
            return base.Channel.getRKBackResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getOCV4DataForOCV53Async(string data)
        {
            return base.Channel.getOCV4DataForOCV53Async(data);
        }
        
        public System.Threading.Tasks.Task<string> getCSBYHResultAsync(string data)
        {
            return base.Channel.getCSBYHResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getPDResultAsync(string data)
        {
            return base.Channel.getPDResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getWGJCDMResultAsync(string data)
        {
            return base.Channel.getWGJCDMResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upCellProcedureNameAsync(string data)
        {
            return base.Channel.upCellProcedureNameAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getECZYResultAsync(string data)
        {
            return base.Channel.getECZYResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> UpMESBoxtDataAsync(string data)
        {
            return base.Channel.UpMESBoxtDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getZYFeedingResultAsync(string data)
        {
            return base.Channel.getZYFeedingResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> GetLyResultAsync(string data)
        {
            return base.Channel.GetLyResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getrkmaterialAsync(string data)
        {
            return base.Channel.getrkmaterialAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getProductCodeAsync(string data)
        {
            return base.Channel.getProductCodeAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getDGKMResultAsync(string data)
        {
            return base.Channel.getDGKMResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getZJPTJResultAsync(string data)
        {
            return base.Channel.getZJPTJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCellProcessDataAsync(string data)
        {
            return base.Channel.getCellProcessDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCellModelAsync(string data)
        {
            return base.Channel.getCellModelAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getZJMQResultAsync(string data)
        {
            return base.Channel.getZJMQResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> GetCellHistoryDataAsync(string data)
        {
            return base.Channel.GetCellHistoryDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getTBFeedingMaterialResultAsync(string data)
        {
            return base.Channel.getTBFeedingMaterialResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> UpYczyByAsync(string data)
        {
            return base.Channel.UpYczyByAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getDGHJResultAsync(string data)
        {
            return base.Channel.getDGHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCellGradeAsync(string data)
        {
            return base.Channel.getCellGradeAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getDXHKResultAsync(string data)
        {
            return base.Channel.getDXHKResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getOCV0ResultAsync(string data)
        {
            return base.Channel.getOCV0ResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCellOrderDataAsync(string data)
        {
            return base.Channel.getCellOrderDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getFXResultAsync(string data)
        {
            return base.Channel.getFXResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getCellWaterResultAsync(string data)
        {
            return base.Channel.getCellWaterResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> CheckCartonDataAsync(string data)
        {
            return base.Channel.CheckCartonDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getIDCardCheckAsync(string data)
        {
            return base.Channel.getIDCardCheckAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upHCINStateAsync(string data)
        {
            return base.Channel.upHCINStateAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getTBFeedingWIPResultAsync(string data)
        {
            return base.Channel.getTBFeedingWIPResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upMaterailScrapAsync(string data)
        {
            return base.Channel.upMaterailScrapAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upScarapQtyAsync(string data)
        {
            return base.Channel.upScarapQtyAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getOCV3ResultAsync(string data)
        {
            return base.Channel.getOCV3ResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getMHYHResultAsync(string data)
        {
            return base.Channel.getMHYHResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upCheckWaterResultAsync(string data)
        {
            return base.Channel.upCheckWaterResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getYcZyDataSAsync(string data)
        {
            return base.Channel.getYcZyDataSAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upFROUTStateAsync(string data)
        {
            return base.Channel.upFROUTStateAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upFRINStateAsync(string data)
        {
            return base.Channel.upFRINStateAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> CheckMESBoxtDataAsync(string data)
        {
            return base.Channel.CheckMESBoxtDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getFJMQResultAsync(string data)
        {
            return base.Channel.getFJMQResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getUserOpCodesAsync(string data)
        {
            return base.Channel.getUserOpCodesAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getYCHJResultAsync(string data)
        {
            return base.Channel.getYCHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getOCV2ResultAsync(string data)
        {
            return base.Channel.getOCV2ResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upCartonDataAsync(string data)
        {
            return base.Channel.upCartonDataAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getFirstProcessAsync(string data)
        {
            return base.Channel.getFirstProcessAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getHCFRResultAsync(string data)
        {
            return base.Channel.getHCFRResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> checkOperatorAsync(string data)
        {
            return base.Channel.checkOperatorAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getYCZYResultAsync(string data)
        {
            return base.Channel.getYCZYResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getXRAYResultAsync(string data)
        {
            return base.Channel.getXRAYResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upCellExceptionStateAsync(string data)
        {
            return base.Channel.upCellExceptionStateAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getOCV3DataForOCV4Async(string data)
        {
            return base.Channel.getOCV3DataForOCV4Async(data);
        }
        
        public System.Threading.Tasks.Task<string> getZJPHJResultAsync(string data)
        {
            return base.Channel.getZJPHJResultAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> getNGCodeAsync(string data)
        {
            return base.Channel.getNGCodeAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> upRealtimeStatusAsync(string data)
        {
            return base.Channel.upRealtimeStatusAsync(data);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EquipWebServiceActionPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EquipWebServiceActionPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.25.225.79:8086/mes-edi-handler/wisdytech/equipWebService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EquipWebServiceActionClient.GetBindingForEndpoint(EndpointConfiguration.EquipWebServiceActionPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EquipWebServiceActionClient.GetEndpointAddress(EndpointConfiguration.EquipWebServiceActionPort);
        }
        
        public enum EndpointConfiguration
        {
            
            EquipWebServiceActionPort,
        }
    }
}
