//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendService.RPServices")]
    public interface RPServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutMesHeartDatas", ReplyAction="http://tempuri.org/RPServices/PutMesHeartDatasResponse")]
        System.Threading.Tasks.Task<string> PutMesHeartDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutMesAlarmDatas", ReplyAction="http://tempuri.org/RPServices/PutMesAlarmDatasResponse")]
        System.Threading.Tasks.Task<string> PutMesAlarmDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutMesStateDatas", ReplyAction="http://tempuri.org/RPServices/PutMesStateDatasResponse")]
        System.Threading.Tasks.Task<string> PutMesStateDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/EnergyUpload", ReplyAction="http://tempuri.org/RPServices/EnergyUploadResponse")]
        System.Threading.Tasks.Task<string> EnergyUploadAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutMesProcessDatas", ReplyAction="http://tempuri.org/RPServices/PutMesProcessDatasResponse")]
        System.Threading.Tasks.Task<string> PutMesProcessDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutMesRealTimeDatas", ReplyAction="http://tempuri.org/RPServices/PutMesRealTimeDatasResponse")]
        System.Threading.Tasks.Task<string> PutMesRealTimeDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutHuorsDatas", ReplyAction="http://tempuri.org/RPServices/PutHuorsDatasResponse")]
        System.Threading.Tasks.Task<string> PutHuorsDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutOutputDatas", ReplyAction="http://tempuri.org/RPServices/PutOutputDatasResponse")]
        System.Threading.Tasks.Task<string> PutOutputDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutMesWornPartDatas", ReplyAction="http://tempuri.org/RPServices/PutMesWornPartDatasResponse")]
        System.Threading.Tasks.Task<string> PutMesWornPartDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/PutMesResultDatas", ReplyAction="http://tempuri.org/RPServices/PutMesResultDatasResponse")]
        System.Threading.Tasks.Task<string> PutMesResultDatasAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/GetFingerPermissionLevel", ReplyAction="http://tempuri.org/RPServices/GetFingerPermissionLevelResponse")]
        System.Threading.Tasks.Task<string> GetFingerPermissionLevelAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/CheckProductInfo", ReplyAction="http://tempuri.org/RPServices/CheckProductInfoResponse")]
        System.Threading.Tasks.Task<string> CheckProductInfoAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/CheckBomInfo", ReplyAction="http://tempuri.org/RPServices/CheckBomInfoResponse")]
        System.Threading.Tasks.Task<string> CheckBomInfoAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/AutoProduceWIP", ReplyAction="http://tempuri.org/RPServices/AutoProduceWIPResponse")]
        System.Threading.Tasks.Task<string> AutoProduceWIPAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RPServices/GetEquipKeyParams", ReplyAction="http://tempuri.org/RPServices/GetEquipKeyParamsResponse")]
        System.Threading.Tasks.Task<string> GetEquipKeyParamsAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface RPServicesChannel : SendService.RPServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class RPServicesClient : System.ServiceModel.ClientBase<SendService.RPServices>, SendService.RPServices
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RPServicesClient() : 
                base(RPServicesClient.GetDefaultBinding(), RPServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RPServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(RPServicesClient.GetBindingForEndpoint(endpointConfiguration), RPServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RPServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RPServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RPServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RPServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RPServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> PutMesHeartDatasAsync(string data)
        {
            return base.Channel.PutMesHeartDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutMesAlarmDatasAsync(string data)
        {
            return base.Channel.PutMesAlarmDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutMesStateDatasAsync(string data)
        {
            return base.Channel.PutMesStateDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> EnergyUploadAsync(string data)
        {
            return base.Channel.EnergyUploadAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutMesProcessDatasAsync(string data)
        {
            return base.Channel.PutMesProcessDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutMesRealTimeDatasAsync(string data)
        {
            return base.Channel.PutMesRealTimeDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutHuorsDatasAsync(string data)
        {
            return base.Channel.PutHuorsDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutOutputDatasAsync(string data)
        {
            return base.Channel.PutOutputDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutMesWornPartDatasAsync(string data)
        {
            return base.Channel.PutMesWornPartDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> PutMesResultDatasAsync(string data)
        {
            return base.Channel.PutMesResultDatasAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> GetFingerPermissionLevelAsync(string data)
        {
            return base.Channel.GetFingerPermissionLevelAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> CheckProductInfoAsync(string data)
        {
            return base.Channel.CheckProductInfoAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> CheckBomInfoAsync(string data)
        {
            return base.Channel.CheckBomInfoAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> AutoProduceWIPAsync(string data)
        {
            return base.Channel.AutoProduceWIPAsync(data);
        }
        
        public System.Threading.Tasks.Task<string> GetEquipKeyParamsAsync(string data)
        {
            return base.Channel.GetEquipKeyParamsAsync(data);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {
                return new System.ServiceModel.EndpointAddress("http://myserver/RPServices/");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RPServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RPServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding,
        }
    }
}
